branch-defaults:
  master:
    environment: null
    group_suffix: null
environment-defaults:
  dct-ml-api:
    branch: master
    repository: ml-api
global:
  application_name: dct-ml-api
  branch: null
  default_ec2_keyname: JCKBD6
  default_platform: Python 3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
